[sources.docker]
type = "docker_logs"
docker_host = "/var/run/docker.sock"
include_containers = ["auth_template.api", "auth_template.postgres"]

[transforms.json]
type = "remap"
inputs = ["docker"]
drop_on_error = true
source = ".message"

[sinks.console]
type = "console"
inputs = ["json"]
encoding.codec = "json"

[sinks.loki_sync_id]
type = "loki"
inputs = ["json"]
encoding.codec = "json"
labels.event = "log"
labels.container_name = "{{container_name}}"
endpoint = "http://auth_template.loki:3100"
